ALTER TABLE users
    ADD role SMALLINT;

ALTER TABLE users
    ALTER COLUMN role SET NOT NULL;

ALTER TABLE medicine
    ALTER COLUMN description TYPE VARCHAR(255) USING (description::VARCHAR(255));

ALTER TABLE medicine
    ALTER COLUMN name TYPE VARCHAR(255) USING (name::VARCHAR(255));

ALTER TABLE medicine
    ALTER COLUMN unit TYPE VARCHAR(255) USING (unit::VARCHAR(255));